# Generated by Django 6.0.5 on 2026-05-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(choices=[('melody', 'Melody'), ('pop', 'Pop'), ('hiphop', 'HipHop'), ('rock', 'Rock'), ('classical', 'Classical')], max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='song_covers/')),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('plays', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.artist')),
            ],
        ),
    ]
