# Generated by Django 6.0.4 on 2026-05-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_playbackprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='stream_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
