# Generated by Django 6.0.5 on 2026-06-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='stream_count',
        ),
        migrations.AlterField(
            model_name='song',
            name='plays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
