# Generated by Django 6.0.5 on 2026-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_recentlyplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
