# Generated by Django 6.0.5 on 2026-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_favorite_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('artists', 'Artists'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
