# Generated by Django 6.0.5 on 2026-06-15 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='followers',
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
